version: '3.8'
services:
  ms-frontend:
    build:
      context: ./ms-frontend
    ports:
      - '5000:80'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://host.docker.internal:8080}
      - VITE_USE_PROXY=true
